FROM node:18-alpine

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY tsconfig.base.json ./
COPY packages/ ./packages/
COPY services/user-service/ ./services/user-service/

RUN npm install -g pnpm && pnpm install

WORKDIR /app/services/user-service
RUN pnpm prisma:generate
RUN pnpm build

EXPOSE 3002

CMD ["node", "dist/main.js"]
