replicaCount: 1
image:
  repository: english-learning/user-service
  tag: dev
namespace: english-learning-dev
service:
  port: 3002
env:
  - name: NODE_ENV
    value: development
  - name: PORT
    value: "3002"
livenessProbe:
  httpGet:
    path: /api/v1/health
    port: 3002
readinessProbe:
  httpGet:
    path: /api/v1/health
    port: 3002

image:
  pullPolicy: Never
